name: digit_master
description: Digit Master

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_helpers:
    git:
      url: https://bitbucket.org/magicwrighter/flutter-helpers/src/master/lib/flutter_helpers.dart
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  intl: ^0.18.1
  json_annotation: ^4.8.1
  number_to_words_english: ^2.0.2
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.3.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/google_fonts/